version: '3'
services:
  api:
    build:
      context: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0' -p 3001"
    volumes:
      - ./:/app
    privileged: true
    ports:
      - 8080:80